#!/bin/bash
	mkdir -p /tmp/netext73
	cd /tmp/netext73
	source /opt/NeteXt73/procedury
	naglowek > instaluj.sh
	instaluj_gcc instaluj_nowy >> instaluj.sh
	bash instaluj.sh
	rm -f /tmp/netext73/*
#firmware
	cp -f /opt/NeteXt73-pakiety/iwlwifi/*.ucode /lib/firmware/
	mkdir -p /lib/firmware/ath10k/QCA9377/hw1.0
	rm -f /lib/firmware/ath10k/QCA9377/hw1.0/*
	cp -f /opt/NeteXt73-pakiety/QCA9377/* /lib/firmware/ath10k/QCA9377/hw1.0/
	mkdir -p /lib/firmware/i915/
	cp -f /opt/NeteXt73-pakiety/i915/* /lib/firmware/i915/
exit 0
