#!/bin/bash
	mkdir -p /tmp/netext73
	cd /tmp/netext73
	source /opt/NeteXt73/procedury
	naglowek > instaluj.sh
	instaluj_gcc instaluj_nowy >> instaluj.sh
	bash instaluj.sh
	rm -f /tmp/netext73/*
#firmware
	cp -f /opt/NeteXt73-pakiety/iwlwifi/*.ucode /lib/firmware/
exit 0
